pip install lxml
pip install pypiwin32
pip install pandas
pip install numpy
pip install bs4
pip install requests
pip install send2trash
pip install winshell
pip install matplotlib
pip install openpyxl